export default function AnalysisMockups() {
  return (
    <div className="mt-8 space-y-10">
      {/* ── Section 1: Anomaly Alert ── */}
      <div>
        <p className="text-[10px] font-bold tracking-widest text-muted uppercase mb-2">
          Anomaly Detection
        </p>

        <div className="rounded-lg overflow-hidden shadow-md bg-[#2b2b2b] text-white p-5">
          {/* Bot header */}
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-full bg-[#7B68EE] flex items-center justify-center text-xs font-bold shrink-0">
              AI
            </div>
            <div>
              <span className="font-semibold text-sm">FP&amp;A Bot</span>
              <span className="text-[#999] text-xs ml-2">Today 8:02 AM</span>
            </div>
          </div>

          {/* Message body */}
          <div className="text-sm leading-relaxed pl-12">
            <p className="mb-3">
              <span className="font-bold">FP&amp;A Anomaly Alert</span>{' '}
              &mdash; 2 divisions exceed the 20% variance threshold for
              February 2026:
            </p>

            <ul className="list-disc list-inside space-y-1.5 mb-4">
              <li>
                <span className="font-bold">Crane Services</span> &mdash;
                $2,100,000 actual vs $1,600,000 budget{' '}
                <span className="text-red-400 font-semibold">(+31.3%)</span>
              </li>
              <li>
                <span className="font-bold">Energy</span> &mdash; $890,000
                actual vs $1,100,000 budget{' '}
                <span className="text-blue-400 font-semibold">(-19.1%)</span>
              </li>
            </ul>

            <p className="text-[#ccc] mb-4">
              Action recommended: Review Crane Services Hilo project costs and
              Energy Kapolei mobilization timeline.
            </p>

            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              className="text-steel hover:underline text-sm font-medium"
            >
              View in Power BI &rarr;
            </a>
          </div>
        </div>
      </div>

      {/* ── Section 2: Variance Commentary ── */}
      <div>
        <p className="text-[10px] font-bold tracking-widest text-muted uppercase mb-2">
          Variance Commentary
        </p>

        <div className="bg-white rounded-lg shadow-md p-6">
          <h3 className="text-navy font-bold text-base mb-5">
            AI-Generated Variance Commentary — February 2026
          </h3>

          <div className="space-y-5">
            {/* Crane Services — over budget */}
            <div className="flex rounded-md overflow-hidden border border-gray-100">
              <div className="w-1.5 bg-red-500 shrink-0" />
              <div className="p-4 flex-1">
                <h4 className="font-bold text-navy text-sm mb-1.5">
                  Crane Services
                </h4>
                <p className="text-dark text-sm leading-relaxed">
                  Crane Services came in $500K (31.3%) over budget for February,
                  primarily driven by unforecasted equipment maintenance costs on
                  the Hilo project. The project manager submitted a reforecast
                  last week reflecting this overage through Q2. Recommend
                  reviewing the Hilo maintenance contract terms.
                </p>
                <p className="text-muted text-[11px] mt-2 italic">
                  Generated by Claude AI
                </p>
              </div>
            </div>

            {/* Energy — under budget */}
            <div className="flex rounded-md overflow-hidden border border-gray-100">
              <div className="w-1.5 bg-blue-500 shrink-0" />
              <div className="p-4 flex-1">
                <h4 className="font-bold text-navy text-sm mb-1.5">Energy</h4>
                <p className="text-dark text-sm leading-relaxed">
                  Energy Division was $210K (19.1%) under budget for February,
                  reflecting delayed mobilization on the Kapolei solar project.
                  The delay is weather-related and the PM expects to catch up in
                  March. No reforecast needed at this time.
                </p>
                <p className="text-muted text-[11px] mt-2 italic">
                  Generated by Claude AI
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
